# version: "3.8"
networks:
  app-network:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "8001:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./server:/usr/src/server
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./server
          target: /usr/src/server
          ignore:
            - node_modules/
        - action: rebuild
          path: package*.json

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/client
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./client
          target: /usr/src/client
          ignore:
            - node_modules/
        - action: rebuild
          path: package*.json

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: admin
    ports:
      - "4000:4000"
    depends_on:
      - server
    volumes:
      - ./admin:/usr/src/admin
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./admin
          target: /usr/src/admin
          ignore:
            - node_modules/
        - action: rebuild
          path: package*.json

volumes:
  mongo-data:
